// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoYT_Bc5RYcLfQIJ0-ZjRo4XTIITaeHRk',
    appId: '1:1073140207576:web:1e8a03415157be9966ecad',
    messagingSenderId: '1073140207576',
    projectId: 'attendease-4f20e',
    authDomain: 'attendease-4f20e.firebaseapp.com',
    storageBucket: 'attendease-4f20e.firebasestorage.app',
    measurementId: 'G-VF2XDTQ9SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd1ntHMhRM6EAkwFawDjLU4LPS_tmcSZY',
    appId: '1:1073140207576:android:7dcb19d253b21c4a66ecad',
    messagingSenderId: '1073140207576',
    projectId: 'attendease-4f20e',
    storageBucket: 'attendease-4f20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJfzOloTdciFnceuNsX__UDaSlQ7D-hxU',
    appId: '1:1073140207576:ios:74a385581ec4d60366ecad',
    messagingSenderId: '1073140207576',
    projectId: 'attendease-4f20e',
    storageBucket: 'attendease-4f20e.firebasestorage.app',
    iosBundleId: 'com.example.adminattendease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJfzOloTdciFnceuNsX__UDaSlQ7D-hxU',
    appId: '1:1073140207576:ios:74a385581ec4d60366ecad',
    messagingSenderId: '1073140207576',
    projectId: 'attendease-4f20e',
    storageBucket: 'attendease-4f20e.firebasestorage.app',
    iosBundleId: 'com.example.adminattendease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoYT_Bc5RYcLfQIJ0-ZjRo4XTIITaeHRk',
    appId: '1:1073140207576:web:1c319dd126dd725166ecad',
    messagingSenderId: '1073140207576',
    projectId: 'attendease-4f20e',
    authDomain: 'attendease-4f20e.firebaseapp.com',
    storageBucket: 'attendease-4f20e.firebasestorage.app',
    measurementId: 'G-SJ88MEG3YY',
  );

}